function_info:
  count:
    name: 'cnt'
    func_type: 'quantitative'
  median:
    name: 'med'
    func_type: 'quantitative'
  year:
    name: 'yr'
    func_type: 'ordinal'
  sum:
    name: 'sum'
    func_type: 'quantitative'
  max:
    name: 'sum'
    func_type: 'quantitative'
  none:
    name: 'none'
    func_type: 'ordinal'

chart_info:
  Bar Chart: 'Bar'
  Pivot Table: 'Automatic'
  Pie Chart: 'Pie'
